pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Introduction.html ../../Introduction.md --template=./templates/clean_menu.html
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 1\:\ Let\'s\ Start\ with\ the\ Bootloader.html ../../Chapter\ 1\:\ Let\'s\ Start\ with\ the\ Bootloader.md --template=./templates/clean_menu.html --number-offset=0
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 2\:\ An\ Overview\ of\ x86\ Architecture.html ../../Chapter\ 2\:\ An\ Overview\ of\ x86\ Architecture.md --template=./templates/clean_menu.html  --number-offset=1
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 3\:\ The\ Progenitor\ of\ 539kernel.html ../../Chapter\ 3\:\ The\ Progenitor\ of\ 539kernel.md --template=./templates/clean_menu.html  --number-offset=2
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 4\:\ Process\ Management.html ../../Chapter\ 4\:\ Process\ Management.md --template=./templates/clean_menu.html --number-offset=3
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 5\:\ Memory\ Management.html ../../Chapter\ 5\:\ Memory\ Management.md --template=./templates/clean_menu.html  --number-offset=4
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 6\:\ Filesystems.html ../../Chapter\ 6\:\ Filesystems.md --template=./templates/clean_menu.html  --number-offset=5
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/Chapter\ 7\:\ What\'s\ Next\?.html ../../Chapter\ 7\:\ What\'s\ Next\?.md --template=./templates/clean_menu.html  --number-offset=6
pandoc --top-level-division=chapter --listings --filter pandoc-fignos -H ../PDF/tex_setup/listings-setup.tex -o book/References.html ../../References.md --template=./templates/clean_menu.html
